### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by billskar23** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#19]
During the execution of this command:

`from src.utils.data_utils import compact_to_expanded`

I get the error: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 2
      1 # Reading Blocks 0-7
----> 2 from src.utils.data_utils import compact_to_expanded

ModuleNotFoundError: No module named 'src'

When I try to install src with `pip install src` as stated [here](https://pypi.org/project/src/#description), I get the following error: 

Collecting src
  Using cached src-0.0.7.zip (6.3 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: src
  Building wheel for src (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/src
      copying src/__init__.py -> build/lib/src
      running egg_info
      writing src.egg-info/PKG-INFO
      writing dependency_links to src.egg-info/dependency_links.txt
      deleting src.egg-info/entry_points.txt
      writing requirements to src.egg-info/requires.txt
      writing top-level names to src.egg-info/top_level.txt
      reading manifest file 'src.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.rst'
      writing manifest file 'src.egg-info/SOURCES.txt'
      /Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rl/7k9wy1rj49b16tfgl8dttf200000gn/T/pip-install-t58cj2_l/src_44b4321ef9494d748a5c8d74e2d549ea/setup.py", line 70, in <module>
          setup(
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 292, in run
          install = self.reinitialize_command('install',
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 221, in reinitialize_command
          cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 311, in reinitialize_command
          return self.distribution.reinitialize_command(command, reinit_subcommands)
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 953, in reinitialize_command
          for sub in command.get_sub_commands():
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 329, in get_sub_commands
          if method is None or method(self):
        File "/Users/bills/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 787, in has_lib
          self.distribution.has_pure_modules() or self.distribution.has_ext_modules()
      AttributeError: 'NoneType' object has no attribute 'has_pure_modules'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for src
  Running setup.py clean for src
Failed to build src
Installing collected packages: src
  Running setup.py install for src ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for src did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running install
      You've probably made a mistake here and are trying to install from a 'src' directory which doesn't exist.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> src

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Has anyone faced the same issue? I am using python version 3.10.9 on macOS (M2) with jupyter.

**Comment by manujosephv** [comment]
'src' is not a pip install package. It is. Folder included in the GitHub repo.

Have you followed the instructions in the book or the GitHub repo Readme? 

If your folder structure don't look like the expected one, you my fc these errors.

**Comment by billskar23** [comment]
> 

Thank you very much for the clarification. The truth is that I directly opened the notebooks from a different venv. After I created the modern_ts venv everything went perfectly.

**Comment by lbhansali** [comment]
Hi, 
I am facing the same error. I am running it from the modern_ts env and have the folder structure as suggested. 
Could you please suggest?
Thanks.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/14540495/233838819-9f68cf90-1fbf-4480-857f-e18ee14967ab.png">
