### ISSUE TITLE
Issues getting environment properly installed on M1 Mac

### ISSUE THREAD

**Issue by davidcolton** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#4]
Any help you'd be able to offer to get the development environment setup and working on an M1 Mac would be greatly appreciated.

The log of the conda command is attached.

Thanks.

[conda_error.log](https://github.com/PacktPublishing/Modern-Time-Series-Forecasting-with-Python/files/10424498/conda_error.log)

**Comment by manujosephv** [comment]
These dependency errors are notoriously hard to figure out. One way to try and resolve is to unpin versions in the conda file one by one.

for instance:
Try changing `statsforecast==0.6.0`  to `statsforecast>=0.6.0`
and `python-kaleido==0.1.0` to `python-kaleido>=0.1.0`

And if that's also not working, 
`- u8darts<=0.19.0` to `- u8darts==0.19.0` or `- u8darts>=0.19.0`

While this can resolve the conda dependency issues, there is a small risk that some code may not work.

**Comment by koen-dejonghe** [comment]
I have followed the instructions for statsforecast and python-kaleido. Seems to work, but then:
```
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/opt/homebrew/anaconda3/envs/modern_ts/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/.../Modern-Time-Series-Forecasting-with-Python/condaenv.3kbl5r_a.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/manujosephv/pytorch_tabular.git@76e83fb (from -r /Users/.../Modern-Time-Series-Forecasting-with-Python/condaenv.3kbl5r_a.requirements.txt (line 8))
  Cloning https://github.com/manujosephv/pytorch_tabular.git (to revision 76e83fb) to /private/var/folders/wy/v6f0ncw16k58dwlsf1jjph7c0000gq/T/pip-req-build-_6pcpbj7
  Resolved https://github.com/manujosephv/pytorch_tabular.git to commit 76e83fb
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/manujosephv/pytorch_tabular.git /private/var/folders/wy/v6f0ncw16k58dwlsf1jjph7c0000gq/T/pip-req-build-_6pcpbj7
  WARNING: Did not find branch or tag '76e83fb', assuming revision or ref.
  Running command git checkout -q 76e83fb
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in pytorch_tabular setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          protobuf<=3.20.*
                  ~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

**Comment by koen-dejonghe** [comment]
`fancyimpute` also does not install

**Comment by Richdadua** [comment]
...
>   WARNING: Did not find branch or tag '76e83fb', assuming revision or ref.
>   Running command git checkout -q 76e83fb
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [3 lines of output]
>       error in pytorch_tabular setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
>           protobuf<=3.20.*
>                   ~~~~~~^
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> 
> failed
> 
> CondaEnvException: Pip failed
> ```
I got exactly the same error

**Comment by manujosephv** [comment]
@koen-dejonghe I think you can safely skip fancyimpute. It is a problematic package. The other error, let me dig into and figure out.

**Comment by manujosephv** [comment]
As of 22.0, `pip` has made some changes which might be causing this issue. I've seen this for other libraries as well.
[Issue on packaging](https://github.com/pypa/packaging/issues/645)

So, this is the solution:

I have removed `timesynth` and `fancyimpute` from the anaconda env. That along with the changes to `statsforecast` and `python-kaleido` make it working in my M1 Pro. (I haven't checked in `statsforecast` and `python-kaleido` changes because it seems to be Mac specific. I'll probably add it to the Readme as well.

Let me know if this works for you so that I can pin the issue and add it to readme.

**Comment by koen-dejonghe** [comment]
With the new `anaconda_env.yml` , the conda environment installs without issues on my machine.
Thank you very much.

**Comment by fip17** [comment]
Mac M2/M1 problem:  AssertionError: Torch not compiled with CUDA enabled
I did the version corrections for statsforecast and python-kaleido and used mamba

**Comment by dcschw** [comment]
Trying to install the environment on a M2 Macbook Air with the latest anaconda_env.yml and statsforecast>=0.6.0 and
python-kaleido>=0.1.0 leads to the below error message.

Any help with resolving this would be much appreciated.

```
Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/manujosephv/pytorch_tabular.git /private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-req-build-kdxixgmy
  Running command git checkout -b modern_ts_freeze --track origin/modern_ts_freeze
  Switched to a new branch 'modern_ts_freeze'
  branch 'modern_ts_freeze' set up to track 'origin/modern_ts_freeze'.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/daniels/anaconda3/envs/modern_ts/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/daniels/anaconda3/envs/modern_ts/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/daniels/anaconda3/envs/modern_ts/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/mm/55vl94nd119gsfty5_1q66q40000gn/T/pip-build-env-pk92viix/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed
```
